# Generated by Django 5.0.6 on 2024-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
