# Generated by Django 5.0.6 on 2024-05-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_borrowedbook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='books', to='bookapp.category'),
        ),
    ]
